version: "3.9"

services:
  backend:
    build: ./GreenBite-backend
    container_name: greenbite-backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./GreenBite-backend:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./GreenBite-backend/.env


  db:
    image: postgres:15
    container_name: greenbite-db
    environment:
      POSTGRES_DB: greenbite
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: