version: '3.9'

services:

  backend:
    build: ./GreenBite-backend
    container_name: greenbite-backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./GreenBite-backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_NAME=greenbite
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432

  
  frontend:
    build: ./GreenBite-frontend
    container_name: greenbite-frontend
    volumes:
      - ./GreenBite-frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: ["npm", "run", "dev", "--", "--host"]


  db:
    image: postgres:15
    container_name: greenbite-db
    environment:
      POSTGRES_DB: greenbite
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:

