services:
  backend:
    build: ./GreenBite-backend
    container_name: greenbite-backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./GreenBite-backend:/app
    env_file:
      - ./GreenBite-backend/.env
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - DB_NAME=greenbite
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_URL=redis://redis:6379/1
      # - OPENAI_API_KEY=${OPENAI_API_KEY}
      - RUN_MIGRATIONS=1
      - BOOTSTRAP_ONCE=1
      # run these only when you want
      - IMPORT_MEALDB=1
      - TOKENIZE_INGREDIENTS=1
      - BUILD_EMBEDDINGS=1

      - MEALDB_LIMIT=0
      - MEALDB_SLEEP=0.25
      - TOKENS_BATCH_SIZE=300
      - TOKENS_LIMIT=0

  celery:
    build: ./GreenBite-backend
    container_name: greenbite-celery
    command: celery -A project worker --loglevel=info
    volumes:
      - ./GreenBite-backend:/app
    env_file:
      - ./GreenBite-backend/.env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - DB_NAME=greenbite
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_URL=redis://redis:6379/1  
      - RUN_MIGRATIONS=1
      - RUN_MAKEMIGRATIONS_MERGE=0

      - BOOTSTRAP_ONCE=1

      # don't run heavy jobs in celery container
      - IMPORT_MEALDB=0
      - TOKENIZE_INGREDIENTS=0
      - EMBED_MEALS=1
      

  db:
    image: postgres:15
    container_name: greenbite-db
    environment:
      POSTGRES_DB: greenbite
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: greenbite-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  postgres_data:
  redis_data:
